// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { createRequire } = require('node:module')
require = createRequire(__filename)

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      nativeBinding = require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./pg-embedded.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pg-ts/pg-embedded-android-arm64')
        const bindingPackageVersion = require('@pg-ts/pg-embedded-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./pg-embedded.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pg-ts/pg-embedded-android-arm-eabi')
        const bindingPackageVersion = require('@pg-ts/pg-embedded-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      try {
        return require('./pg-embedded.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pg-ts/pg-embedded-win32-x64-msvc')
        const bindingPackageVersion = require('@pg-ts/pg-embedded-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./pg-embedded.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pg-ts/pg-embedded-win32-ia32-msvc')
        const bindingPackageVersion = require('@pg-ts/pg-embedded-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./pg-embedded.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pg-ts/pg-embedded-win32-arm64-msvc')
        const bindingPackageVersion = require('@pg-ts/pg-embedded-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./pg-embedded.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('@pg-ts/pg-embedded-darwin-universal')
      const bindingPackageVersion = require('@pg-ts/pg-embedded-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./pg-embedded.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pg-ts/pg-embedded-darwin-x64')
        const bindingPackageVersion = require('@pg-ts/pg-embedded-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./pg-embedded.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pg-ts/pg-embedded-darwin-arm64')
        const bindingPackageVersion = require('@pg-ts/pg-embedded-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./pg-embedded.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pg-ts/pg-embedded-freebsd-x64')
        const bindingPackageVersion = require('@pg-ts/pg-embedded-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./pg-embedded.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pg-ts/pg-embedded-freebsd-arm64')
        const bindingPackageVersion = require('@pg-ts/pg-embedded-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./pg-embedded.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@pg-ts/pg-embedded-linux-x64-musl')
          const bindingPackageVersion = require('@pg-ts/pg-embedded-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./pg-embedded.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@pg-ts/pg-embedded-linux-x64-gnu')
          const bindingPackageVersion = require('@pg-ts/pg-embedded-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./pg-embedded.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@pg-ts/pg-embedded-linux-arm64-musl')
          const bindingPackageVersion = require('@pg-ts/pg-embedded-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./pg-embedded.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@pg-ts/pg-embedded-linux-arm64-gnu')
          const bindingPackageVersion = require('@pg-ts/pg-embedded-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./pg-embedded.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@pg-ts/pg-embedded-linux-arm-musleabihf')
          const bindingPackageVersion = require('@pg-ts/pg-embedded-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./pg-embedded.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@pg-ts/pg-embedded-linux-arm-gnueabihf')
          const bindingPackageVersion = require('@pg-ts/pg-embedded-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./pg-embedded.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@pg-ts/pg-embedded-linux-riscv64-musl')
          const bindingPackageVersion = require('@pg-ts/pg-embedded-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./pg-embedded.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@pg-ts/pg-embedded-linux-riscv64-gnu')
          const bindingPackageVersion = require('@pg-ts/pg-embedded-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./pg-embedded.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pg-ts/pg-embedded-linux-ppc64-gnu')
        const bindingPackageVersion = require('@pg-ts/pg-embedded-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./pg-embedded.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pg-ts/pg-embedded-linux-s390x-gnu')
        const bindingPackageVersion = require('@pg-ts/pg-embedded-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./pg-embedded.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pg-ts/pg-embedded-openharmony-arm64')
        const bindingPackageVersion = require('@pg-ts/pg-embedded-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./pg-embedded.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pg-ts/pg-embedded-openharmony-x64')
        const bindingPackageVersion = require('@pg-ts/pg-embedded-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./pg-embedded.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pg-ts/pg-embedded-openharmony-arm')
        const bindingPackageVersion = require('@pg-ts/pg-embedded-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.2.1+pg17.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.1+pg17.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  try {
    nativeBinding = require('./pg-embedded.wasi.cjs')
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      loadErrors.push(err)
    }
  }
  if (!nativeBinding) {
    try {
      nativeBinding = require('@pg-ts/pg-embedded-wasm32-wasi')
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        loadErrors.push(err)
      }
    }
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      { cause: loadErrors }
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.ConnectionInfo = nativeBinding.ConnectionInfo
module.exports.PgBasebackupTool = nativeBinding.PgBasebackupTool
module.exports.PgDumpallTool = nativeBinding.PgDumpallTool
module.exports.PgDumpTool = nativeBinding.PgDumpTool
module.exports.PgIsReadyTool = nativeBinding.PgIsReadyTool
module.exports.PgRestoreTool = nativeBinding.PgRestoreTool
module.exports.PgRewindTool = nativeBinding.PgRewindTool
module.exports.PostgresInstance = nativeBinding.PostgresInstance
module.exports.PsqlTool = nativeBinding.PsqlTool
module.exports.getPackageVersion = nativeBinding.getPackageVersion
module.exports.getPostgreSqlVersion = nativeBinding.getPostgreSqlVersion
module.exports.getVersionInfo = nativeBinding.getVersionInfo
module.exports.initLogger = nativeBinding.initLogger
module.exports.InstanceState = nativeBinding.InstanceState
module.exports.logDebug = nativeBinding.logDebug
module.exports.logError = nativeBinding.logError
module.exports.logInfo = nativeBinding.logInfo
module.exports.LogLevel = nativeBinding.LogLevel
module.exports.logTrace = nativeBinding.logTrace
module.exports.logWarn = nativeBinding.logWarn
module.exports.PgBasebackupCheckpoint = nativeBinding.PgBasebackupCheckpoint
module.exports.PgBasebackupFormat = nativeBinding.PgBasebackupFormat
module.exports.PgBasebackupWalMethod = nativeBinding.PgBasebackupWalMethod
module.exports.PgDumpFormat = nativeBinding.PgDumpFormat
module.exports.PgRestoreFormat = nativeBinding.PgRestoreFormat
module.exports.PostgresError = nativeBinding.PostgresError
